cloud:
  aws:
    credentials:
      accessKey: AKIAX25ZL5T4CPD6HX4L     # AWS IAM AccessKey 적기
      secretKey: Xw/oRuI6HVodKQR9SsfMmSboi8wKxEeGLAED8Qq9   # AWS IAM SecretKey 적기
    s3:
      bucket: rsupport-notice-management   # ex) marryting-gyunny
      dir: /image # ex) /gyunny
    region:
      static: us-east-1
    stack:
      auto: false

spring:
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    generate-ddl: on
    hibernate:
      format_sql: true
      use_sql_comments: true
      show_sql : true
      ddl-auto: none
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    username: SA
    password:
  sql:
    init:
      mode: embedded
      data-locations:
        classpath: data-h2.sql
      schema-locations:
        classpath: schema-h2.sql

logging:
  level:
    org.hibernate.sql: